// queries.js
const select1 = `SELECT IT.CD_PRODUTO, P.DS_PRODUTO 
FROM ENT_PRO ENT
INNER JOIN ITENT_PRO IT ON IT.CD_ENT_PRO = ENT.CD_ENT_PRO
INNER JOIN ESTOQUE E ON E.CD_ESTOQUE = ENT.CD_ESTOQUE
INNER JOIN PRODUTO P ON P.CD_PRODUTO = IT.CD_PRODUTO
WHERE E.CD_MULTI_EMPRESA = 5
AND IT.CD_ENT_PRO = 705
AND IT.CD_ITENT_PRO NOT IN (SELECT CD_ITENT_PRO FROM ITLOT_ENT)`;

module.exports = { select1 };
